import type { CollectionId, Record } from "@/lib/types";

// Seed data extracted from the team's working spreadsheet (Cribl web/content
// team). This is a representative subset so the grid is populated and the
// field mapping is exercised end to end. It will be replaced by live Jira data
// once the JiraAdapter is wired up.

let counter = 0;
const id = () => `seed-${++counter}`;

const content = (f: Record["fields"], jiraKey: string | null = null): Record => ({
  id: id(),
  jiraKey,
  fields: f,
});

export const SEED: { [K in CollectionId]: Record[] } = {
  content: [
    content(
      {
        searchType: "Both",
        status: "New",
        quarter: "Q2",
        type: "Core",
        targetPrompt: "What are the top log collection and analysis tools?",
        keyword: "Best Log Collection Platforms",
        volume: 29,
        format: "Listicle",
        topic: "Log / Event / Trace / Metrics Management",
        subtopic: "Log Collection",
        contentType: "Resources",
        stage: "With Marketing Strat",
        priorityBucket: "Visibility",
        priorityLevel: "1. High",
        owner: "Bill",
        startMonth: "Apr-26",
        endMonth: "May-26",
        publishedUrl: "",
      },
      "WEB-1022"
    ),
    content(
      {
        searchType: "Both",
        status: "New",
        quarter: "",
        type: "Core",
        targetPrompt: "What are the top log monitoring tools available?",
        keyword: "best log monitoring tools",
        volume: 28,
        format: "Listicle",
        topic: "Log / Event / Trace / Metrics Management",
        subtopic: "Log Monitoring",
        contentType: "Resources",
        stage: "With Marketing Strat",
        priorityBucket: "Visibility",
        priorityLevel: "1. High",
        owner: "Bill",
        startMonth: "TBD",
        endMonth: "",
        publishedUrl: "",
      },
      "WEB-1084"
    ),
    content(
      {
        searchType: "",
        status: "New",
        quarter: "Q2",
        type: "Core",
        targetPrompt: "Which data lake platforms are best?",
        keyword: "Best data lake platforms",
        volume: 27,
        format: "Listicle",
        topic: "Data Strategy",
        subtopic: "Data lakes",
        contentType: "Resources",
        stage: "With Marketing Strat",
        priorityBucket: "Visibility",
        priorityLevel: "1. High",
        owner: "Felicia",
        startMonth: "TBD",
        endMonth: "",
        publishedUrl: "",
      },
      "WEB-1060"
    ),
    content(
      {
        searchType: "LLM",
        status: "New",
        quarter: "Q2",
        type: "Core",
        targetPrompt: "What are the best data pipeline tools?",
        keyword: "best data pipeline tools",
        volume: 22,
        format: "Listicle",
        topic: "Telemetry Pipeline (Stream)",
        subtopic: "Data Pipelines",
        contentType: "Resources",
        stage: "Planning",
        priorityBucket: "Strategic",
        priorityLevel: "3. Low",
        owner: "Desi",
        startMonth: "TBD",
        endMonth: "",
        publishedUrl: "",
      },
      null
    ),
    content(
      {
        searchType: "LLM",
        status: "New",
        quarter: "Q1",
        type: "Campaign",
        targetPrompt: "How to implement threat detection and incident response?",
        keyword: "",
        volume: 2,
        format: "Long Form",
        topic: "Investigations",
        subtopic: "Incident analysis and response",
        contentType: "Blog",
        stage: "Complete",
        priorityBucket: "Campaign",
        priorityLevel: "3. Low",
        owner: "Felicia",
        startMonth: "Apr-26",
        endMonth: "May-26",
        publishedUrl:
          "https://cribl.io/blog/implementing-threat-detection-and-incident-response-effectively/",
      },
      "WEB-982"
    ),
    content(
      {
        searchType: "LLM",
        status: "New",
        quarter: "Q3",
        type: "Core",
        targetPrompt: "Best practices for log enrichment with business context?",
        keyword: "",
        volume: 2,
        format: "Long Form",
        topic: "Log / Event / Trace / Metrics Management",
        subtopic: "Log Enrichment",
        contentType: "Blog",
        stage: "Recommendations Created",
        priorityBucket: "Strategic",
        priorityLevel: "3. Low",
        owner: "Bill",
        startMonth: "Apr-26",
        endMonth: "May-26",
        publishedUrl: "",
      },
      "WEB-999"
    ),
    content(
      {
        searchType: "Both",
        status: "Current",
        quarter: "",
        type: "Campaign",
        targetPrompt: "How does siem augmentation improve threat detection?",
        keyword: "siem augmentation",
        volume: 2,
        format: "Long Form",
        topic: "SecOps Optimization",
        subtopic: "SIEM Augmentation",
        contentType: "Blog",
        stage: "Planning",
        priorityBucket: "Campaign",
        priorityLevel: "3. Low",
        owner: "Bill, Carlo",
        startMonth: "",
        endMonth: "",
        publishedUrl: "",
      },
      null
    ),
    content(
      {
        searchType: "LLM",
        status: "New",
        quarter: "Q1",
        type: "Visibility",
        targetPrompt: "How to build reliable data pipelines?",
        keyword: "",
        volume: 2,
        format: "Blog",
        topic: "Telemetry Pipeline (Stream)",
        subtopic: "Data Pipelines",
        contentType: "Blog",
        stage: "Complete",
        priorityBucket: "Visibility",
        priorityLevel: "2. Medium",
        owner: "Desi",
        startMonth: "",
        endMonth: "",
        publishedUrl: "https://cribl.io/blog/building-data-pipelines-for-reliability/",
      },
      "WEB-1026"
    ),
  ],

  // Launch deliverables workback tracker — mirrors the team's GTM launch
  // spreadsheet: deliverables grouped by phase, with launch-moment tags, a
  // workback set of dates, and a Responsible owner.
  launch: [
    // Phase 0 — GTM Planning & Alignment
    {
      id: id(),
      fields: {
        phase: "Phase 0 — GTM Planning & Alignment",
        status: "Completed",
        deliverable: "Pre-Planning",
        moment: "Pre-LA",
        startDate: "Mon, Nov. 24",
        finalDate: "Fri, Dec. 19",
        responsible: "Gabby Zurita",
      },
    },
    {
      id: id(),
      fields: {
        phase: "Phase 0 — GTM Planning & Alignment",
        status: "Completed",
        deliverable: "GTM Motion Definition",
        moment: "Pre-LA",
        links: "Visual",
        startDate: "Mon, Nov. 24",
        finalDate: "Fri, Dec. 19",
        responsible: "Chris Hayward",
      },
    },
    {
      id: id(),
      fields: {
        phase: "Phase 0 — GTM Planning & Alignment",
        status: "Ongoing",
        deliverable: "Messaging Brief - Product",
        moment: "Pre-LA",
        dependency: "Includes use cases",
        links: "WIP Brief",
        startDate: "Tue, Dec. 2",
        draftDue: "Tue, Jan. 6",
        approvalsDue: "Tue, Jan. 13",
        finalDate: "Fri, Jan. 16",
        responsible: "Alexandra Gates",
      },
    },
    // Phase 1 — Message Validation & Early Readiness
    {
      id: id(),
      fields: {
        phase: "Phase 1 — Message Validation & Early Readiness",
        status: "Completed",
        deliverable: "ICP Build - Product",
        moment: "Pre-Launch",
        links: "Cribl Search ICP",
        startDate: "Wed, Jan. 14",
        draftDue: "Thu, Jan. 29",
        finalDate: "Fri, Feb. 20",
        responsible: "Felicia Dorng Rachael Dula",
      },
    },
    {
      id: id(),
      fields: {
        phase: "Phase 1 — Message Validation & Early Readiness",
        status: "Ongoing",
        deliverable: "Internal FAQ v1",
        moment: "LA",
        dependency: "Must be ready for Feb. 5 Pit Stop",
        links: "v1 WIP",
        finalDate: "Tue, Feb. 3",
        responsible: "Felicia Dorng",
      },
    },
    {
      id: id(),
      jiraKey: "WEB-984",
      fields: {
        phase: "Phase 1 — Message Validation & Early Readiness",
        status: "Completed",
        deliverable: "One-Pager (Pre-read for CKO)",
        moment: "Pre-CKO",
        links: "One-Pager Doc",
        startDate: "Mon, Jan. 12",
        draftDue: "Tue, Jan. 20",
        approvalsDue: "Fri, Jan. 23",
        intakeForm: "Fri, Jan. 23",
        designComplete: "Fri, Jan. 30",
        finalDate: "Tue, Feb. 3",
        responsible: "Felicia Dorng",
      },
    },
    // Phase 2 — Market Momentum & Field Activation
    {
      id: id(),
      fields: {
        phase: "Phase 2 — Market Momentum & Field Activation",
        status: "Completed",
        deliverable: "Momentum PR",
        moment: "CKO",
        startDate: "Wed, Jan. 28",
        draftDue: "Wed, Feb. 4",
        finalDate: "Wed, Feb. 11",
        responsible: "Rachael King",
      },
    },
    {
      id: id(),
      fields: {
        phase: "Phase 2 — Market Momentum & Field Activation",
        status: "Completed",
        deliverable: "Feb. 26 Pit Stop: Enablement slide deck",
        moment: "Post-CKO",
        dependency: "Compete, target accounts, customer proof from LA",
        links: "Enablement Deck",
        startDate: "Thu, Feb. 5",
        draftDue: "Tue, Feb. 17",
        approvalsDue: "Mon, Feb. 23",
        finalDate: "Thu, Feb. 26",
        responsible: "Rachael Dula",
      },
    },
    {
      id: id(),
      jiraKey: "DEMOS-511",
      fields: {
        phase: "Phase 2 — Market Momentum & Field Activation",
        status: "Completed",
        deliverable: "Partner FAQ (Reseller + Alliances)",
        moment: "Post-CKO",
        links: "Partner FAQ",
        startDate: "Fri, Feb. 6",
        draftDue: "Thu, Feb. 12",
        approvalsDue: "Thu, Feb. 19",
        finalDate: "Thu, Mar. 12",
        responsible: "Alyssa Houk Emily Walters",
      },
    },
    {
      id: id(),
      fields: {
        phase: "Phase 2 — Market Momentum & Field Activation",
        status: "In Progress - Review",
        deliverable: "Competitive Update",
        moment: "Post-CKO",
        dependency: "Share with enablement team",
        startDate: "Mon, Feb. 9",
        draftDue: "Wed, Feb. 18",
        finalDate: "Mon, Feb. 23",
        responsible: "Connor Ivens",
      },
    },
    // Phase 3 — GTM Launch Rollout
    {
      id: id(),
      fields: {
        phase: "Phase 3 — GTM Launch Rollout",
        status: "Completed",
        deliverable: "PR Final + Go Live",
        moment: "GA",
        startDate: "Mon, Mar. 9",
        finalDate: "Wed, Mar. 11",
        responsible: "Rachael King",
      },
    },
    {
      id: id(),
      fields: {
        phase: "Phase 3 — GTM Launch Rollout",
        status: "Completed",
        deliverable: "Release Blog",
        moment: "GA",
        links: "Reintroducing Cribl Search",
        startDate: "Tue, Feb. 17",
        draftDue: "Mon, Mar. 2",
        approvalsDue: "Thu, Mar. 5",
        designComplete: "Mon, Mar. 9",
        webMopsComplete: "Tue, Mar. 10",
        finalDate: "Wed, Mar. 11",
        responsible: "Felicia Dorng",
      },
    },
    {
      id: id(),
      jiraKey: "WEB-922",
      fields: {
        phase: "Phase 3 — GTM Launch Rollout",
        status: "Completed",
        deliverable: "Web Updates",
        moment: "GA",
        dependency: "See full list of page updates",
        links: "Web Updates | WEB-922",
        startDate: "Tue, Jan. 27",
        draftDue: "Fri, Feb. 6",
        approvalsDue: "Fri, Feb. 20",
        intakeForm: "Mon, Feb. 23",
        designComplete: "Wed, Mar. 4",
        webMopsComplete: "Mon, Mar. 9",
        finalDate: "Wed, Mar. 11",
        responsible: "Felicia Dorng Bill Emmett",
      },
    },
    {
      id: id(),
      jiraKey: "DESIGN-2120",
      fields: {
        phase: "Phase 3 — GTM Launch Rollout",
        status: "Completed",
        deliverable: "Architecture Diagram + Data Engine Diagram",
        moment: "GA",
        links: "DESIGN-2120",
        startDate: "Thu, Feb. 5",
        draftDue: "Mon, Feb. 16",
        approvalsDue: "Mon, Feb. 23",
        designComplete: "Fri, Mar. 6",
        finalDate: "Wed, Mar. 11",
        responsible: "Felicia Dorng",
      },
    },
    {
      id: id(),
      fields: {
        phase: "Phase 3 — GTM Launch Rollout",
        status: "In Progress - Review",
        deliverable: "Search Copilot Description Update",
        moment: "GA",
        startDate: "Mon, Feb. 23",
        draftDue: "Thu, Feb. 26",
        approvalsDue: "Tue, Mar. 3",
        webMopsComplete: "Mon, Mar. 9",
        finalDate: "Wed, Mar. 11",
        responsible: "Felicia Dorng",
      },
    },
    {
      id: id(),
      fields: {
        phase: "Phase 3 — GTM Launch Rollout",
        status: "Completed",
        deliverable: "What's New Webinar Live",
        moment: "Post Launch",
        workType: "Webinar",
        autoTickets: "DESIGN-5012, MOPS-3821, SOCIAL-204",
        firedStages: "Scheduled",
        dependency: "Customers only, product-centric",
        links: "Webinar Tracker",
        startDate: "Tue, Mar. 24",
        finalDate: "Tue, Mar. 24",
        responsible: "Sabrina Schipper",
      },
    },
    // Phase 4 — Post-Launch Optimization & Expansion
    {
      id: id(),
      fields: {
        phase: "Phase 4 — Post-Launch Optimization & Expansion",
        status: "Not Started",
        deliverable: "BOFU Demo Video",
        moment: "Post Launch",
        startDate: "Tue, Mar. 31",
        draftDue: "Tue, Apr. 7",
        finalDate: "Tue, Apr. 14",
        responsible: "Felicia Dorng",
      },
    },
    {
      id: id(),
      fields: {
        phase: "Phase 4 — Post-Launch Optimization & Expansion",
        status: "In Progress - On Track",
        deliverable: "CC User Updates",
        moment: "Post Launch",
        dependency: "Dependent on Product timeline",
        startDate: "Wed, Mar. 4",
        finalDate: "Fri, May. 22",
        responsible: "Mariano Romano",
      },
    },
    {
      id: id(),
      jiraKey: "MOPS-3769",
      fields: {
        phase: "Phase 4 — Post-Launch Optimization & Expansion",
        status: "In Progress - On Track",
        deliverable: "Validate TAL w/Field RDs",
        moment: "Post Launch",
        links: "MOPS-3769 | TAL",
        startDate: "Thu, May. 7",
        finalDate: "Mon, May. 18",
        responsible: "Joanna Zheng",
      },
    },
    {
      id: id(),
      fields: {
        phase: "Phase 4 — Post-Launch Optimization & Expansion",
        status: "Scheduled",
        deliverable: "GTM Live (Sales Play)",
        moment: "Launch",
        startDate: "Thu, Jun. 4",
        finalDate: "Thu, Jun. 4",
        responsible: "Rachael Dula",
      },
    },
    {
      id: id(),
      fields: {
        phase: "Phase 4 — Post-Launch Optimization & Expansion",
        status: "Not Started",
        deliverable: "PMM Search Content Audit",
        moment: "Post Launch",
        startDate: "Thu, Mar. 19",
        draftDue: "Thu, Mar. 26",
        finalDate: "Thu, Apr. 2",
        responsible: "Felicia Dorng",
      },
    },
    {
      // Not yet fired — flip Status to "Scheduled" to watch the Webinar
      // playbook open the Design, MOPS, and Content/Social tickets.
      id: id(),
      fields: {
        phase: "Phase 4 — Post-Launch Optimization & Expansion",
        status: "Not Started",
        deliverable: "Customer Webinar — Q3 Search Deep Dive",
        moment: "Post Launch",
        workType: "Webinar",
        dependency: "Auto-opens cross-team tickets when Scheduled",
        startDate: "Mon, Jul. 6",
        finalDate: "Wed, Jul. 22",
        responsible: "Sabrina Schipper",
      },
    },
  ],

  // Tickets opened by workflow automations (mock stand-ins for real Jira
  // issues across team projects). Two were pre-opened by the Webinar playbook
  // for "What's New Webinar Live".
  tickets: [
    {
      id: id(),
      fields: {
        key: "DESIGN-5012",
        summary: "Creative assets package — What's New Webinar Live",
        team: "Design",
        project: "DESIGN",
        status: "In Progress",
        assignee: "Kaycee Carmichael Chiu Hannah Inman",
        due: "Open ASAP after abstract; ~1 week creative turnaround",
        details: "Eblast header • Landing headers • OG image • Social 1200x1200 • Website banner • BrightTalk + PathFactory tiles",
        sourceDeliverable: "What's New Webinar Live",
      },
    },
    {
      id: id(),
      fields: {
        key: "MOPS-3821",
        summary: "Demand Gen What's New Webinar Live — Marketo Program Build",
        team: "Marketing Ops",
        project: "MOPS",
        status: "Done",
        assignee: "Marketing Ops",
        due: "Promo emails 2 weeks / 1 week / 1 day prior",
        details: "Campaign + landing page • Email schedule • Reg UTMs (RSM/BDR/Channel/Web/Social) • PathFactory • BrightTalk syndication",
        sourceDeliverable: "What's New Webinar Live",
      },
    },
    {
      id: id(),
      fields: {
        key: "SOCIAL-204",
        summary: "Promote What's New Webinar Live — organic + field",
        team: "Content / Social",
        project: "SOCIAL",
        status: "To Do",
        assignee: "Hannah Inman Marie Hill",
        due: "As soon as the registration page is live",
        details: "Organic social once banners ready • Send UTMs to Field Channel Marketing • Add to Webinar calendar",
        sourceDeliverable: "What's New Webinar Live",
      },
    },
  ],

  okr: [
    {
      id: id(),
      fields: {
        objectiveNum: 1,
        krNum: "1.1",
        keyResult: "Deliver brand and company wide initiatives to Cribl.io",
        priority: "P0",
        startValue: 0,
        targetValue: 6400,
        expectedValue: 1600,
        actualValue: null,
        progress: "",
        owner: "Mickey",
        objective: "1. Increase discoverability and key conversions across Cribl.io",
      },
    },
    {
      id: id(),
      fields: {
        objectiveNum: 1,
        krNum: "1.3",
        keyResult: "Secure a 17.5% organic CTR on product & solution pages",
        priority: "P0",
        startValue: 70,
        targetValue: 75,
        expectedValue: 75,
        actualValue: 72,
        progress: "96%",
        owner: "Alex / PMM",
        objective: "1. Increase discoverability and key conversions across Cribl.io",
      },
    },
    {
      id: id(),
      fields: {
        objectiveNum: 2,
        krNum: "2.1",
        keyResult:
          "Integrate with core marketing systems to enhance targeting, attribution, and analytics",
        priority: "P1",
        startValue: 0,
        targetValue: 8,
        expectedValue: 2,
        actualValue: null,
        progress: "",
        owner: "Alex",
        objective:
          "2. Unlock a best-in-class web platform to publish, optimize, and measure web content",
      },
    },
    {
      id: id(),
      fields: {
        objectiveNum: 3,
        krNum: "3.2",
        keyResult: "Maintain “Good” Core Web Vitals ratings for ≥75% of users",
        priority: "P1",
        startValue: 65,
        targetValue: 75,
        expectedValue: 68,
        actualValue: 81,
        progress: "100%",
        owner: "Alex",
        objective:
          "3. Ensure Cribl.io is compliant, fast, accessible, and optimized for search and LLMs",
      },
    },
  ],

  quarterPlan: [
    { id: id(), fields: { quarter: "Q1", owner: "Desi", item: "Which observability pipeline solutions are best?" } },
    { id: id(), fields: { quarter: "Q1", owner: "Bill", item: "What are centralized logging best practices in 2026?" } },
    { id: id(), fields: { quarter: "Q1", owner: "Felicia", item: "How to conduct insider threat hunting effectively?" } },
    { id: id(), fields: { quarter: "Q2", owner: "Desi", item: "What are the best data pipeline tools?" } },
    { id: id(), fields: { quarter: "Q2", owner: "Bill", item: "What are the best log monitoring tools?" } },
    { id: id(), fields: { quarter: "Q2", owner: "Felicia", item: "Which data lake platforms are best?" } },
    { id: id(), fields: { quarter: "Q2", owner: "Carlo", item: "Best security log management tools for SOC?" } },
    { id: id(), fields: { quarter: "Q2", owner: "Judith", item: "How to optimize log data collection workflows?" } },
  ],

  topicOwners: [
    { id: id(), fields: { topic: "Edge", primaryPMM: "Desi", secondaryPMM: "Judith" } },
    { id: id(), fields: { topic: "Telemetry / O11y Pipeline (Stream)", primaryPMM: "Desi", secondaryPMM: "Holly" } },
    { id: id(), fields: { topic: "Data Management", primaryPMM: "Bill", secondaryPMM: "" } },
    { id: id(), fields: { topic: "Log / Event / Trace / Metrics Management", primaryPMM: "Bill", secondaryPMM: "" } },
    { id: id(), fields: { topic: "Search", primaryPMM: "Felicia", secondaryPMM: "" } },
    { id: id(), fields: { topic: "Agentic Telemetry", primaryPMM: "Alex", secondaryPMM: "Judith" } },
    { id: id(), fields: { topic: "Investigations", primaryPMM: "Felicia", secondaryPMM: "" } },
    { id: id(), fields: { topic: "SecOps Optimization", primaryPMM: "Carlo", secondaryPMM: "" } },
    { id: id(), fields: { topic: "SIEM Migration", primaryPMM: "Desi", secondaryPMM: "Holly" } },
  ],
};
